### ISSUE TITLE
btw this course is giving unhandled promise rejection error.

### ISSUE THREAD

**Issue by cristian-gabbanini** [cristian-gabbanini/fem-downloader#4]
btw this course is giving unhandled promise rejection error.

https://frontendmasters.com/courses/javascript-hard-parts

[https://i.imgur.com/1TQD59a.png](url)

_Originally posted by @pubgrad in https://github.com/cristian-gabbanini/fem-downloader/issues/3#issuecomment-491622817_

**Comment by pubgrad** [comment]
Some other courses were giving similar error like the good parts and the web by douglas crockford

**Comment by cristian-gabbanini** [comment]
> btw this course is giving unhandled promise rejection error.
> 
> https://frontendmasters.com/courses/javascript-hard-parts
> 
> [https://i.imgur.com/1TQD59a.png](url)
> 
> _Originally posted by @pubgrad in [#3 (comment)](https://github.com/cristian-gabbanini/fem-downloader/issues/3#issuecomment-491622817)_

I'm sorry but I cannot see the image; could you be so kind to repost it?

**Comment by pubgrad** [comment]
https://i.imgur.com/1TQD59a.png

**Comment by rs459** [comment]
Titles contains slash '/', and before creating directory this kind of characters should be replaced. Creation of folder fail since this character is not allowed for directory name.
